### ISSUE TITLE
导入报错请教

### ISSUE THREAD

**Issue by ximiluliyi** [bit4woo/knife#10]
大佬，我在extender模块导入压缩包里面src目录里面的插件 然后显示：
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.y3e.a(Unknown Source)
	at burp.y3e.<init>(Unknown Source)
	at burp.fme.a(Unknown Source)
	at burp.q0h.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

烦请大佬赐教， 百度已经查过解决办法，没有解决问题，所以还是问大佬吧

**Comment by bit4woo** [comment]
下载jar包导入，不是源码的压缩包。你是不是弄错了
https://github.com/bit4woo/knife/releases
