### ISSUE TITLE
配置

### ISSUE THREAD

**Issue by lanjian747** [bit4woo/knife#40]
想问一下为啥2.1的burp装这个插件后菜单选项没变化，右键没有那些选项，burp2.1，Java1.8

**Comment by lanjian747** [comment]
![图片](https://user-images.githubusercontent.com/69381160/141105147-ec71405e-446a-472d-a69f-a387313dbb12.png)

**Comment by bit4woo** [comment]
请关注错误输出，没有错误输出没有办法进行问题定位。如果无错误，可以尝试重新通过console启动burp程序，并重新加载插件。

![image](https://user-images.githubusercontent.com/8793481/141107352-5bdb906a-5a2d-4933-896d-f0a948b7347c.png)

**Comment by lanjian747** [comment]
刚才更新了knife1.9，右键无knife的问题已解决，但是在安装上插件后有如下报错
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseFloat(Unknown Source)
	at java.lang.Float.parseFloat(Unknown Source)
	at U2C.U2CTabFactory.needJSON(U2CTabFactory.java:41)
	at U2C.U2CTab.isEnabled(U2CTabFactory.java:93)
	at burp.b89.a(Unknown Source)
	at burp.f7g.a(Unknown Source)
	at burp.f7g.a(Unknown Source)
	at burp.b91.a(Unknown Source)
	at burp.cbu.b(Unknown Source)
	at burp.f7g.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Unknown Source)
	at javax.swing.JComponent.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Unknown Source)
	at javax.swing.JComponent.addNotify(Unknown Source)
	at java.awt.Container.addImpl(Unknown Source)
	at javax.swing.JTabbedPane.insertTab(Unknown Source)
	at burp.f7t.a(Unknown Source)
	at burp.f7t.insertTab(Unknown Source)
	at javax.swing.JTabbedPane.addTab(Unknown Source)
	at burp.ft2.a(Unknown Source)
	at burp.b91.b(Unknown Source)
	at burp.b91.lambda$extensionConfigChanged$4(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by lanjian747** [comment]
谢谢师傅解答！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月10日(星期三) 晚上7:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bit4woo/knife] 配置 (Issue #40)





 
请关注错误输出，没有错误输出没有办法进行问题定位。如果无错误，可以尝试重新通过console启动burp程序，并重新加载插件。
 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bit4woo** [comment]
上面这个错误是取burp的版本号导致的，有异常捕获，不影响正常功能。
