### ISSUE TITLE
导入报告找不到com/alibaba/fastjson/JSONObject类

### ISSUE THREAD

**Issue by daliang987** [bit4woo/knife#5]
项目引用了alibaba的fastjson类，但是通过eclipse导出的时候，不会又这个类包含在jar文件中。如何解决。

`java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSONObject
	at config.ConfigEntry.ToJson(ConfigEntry.java:67)
	at config.ConfigTableModel.getConfigJsons(ConfigTableModel.java:51)
	at config.GUI.getAllConfig(GUI.java:354)
	at burp.BurpExtender.initConfig(BurpExtender.java:148)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.u2e.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSONObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
`

**Comment by bit4woo** [comment]
我用的是maven，请使用maven进行打包
