### ISSUE TITLE
插件加载异常NullPointerException

### ISSUE THREAD

**Issue by crazy-zxx** [bit4woo/knife#70]
Burpsuite版本： v2023.11.1.1

加载插件报错：
java.lang.NullPointerException: Cannot invoke "javax.swing.table.TableModel.addTableModelListener(javax.swing.event.TableModelListener)" because the return value of "javax.swing.JTable.getModel()" is null
	at burp.theme.BurpTableUI.installListeners(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.installUI(BasicTableUI.java:1441)
	at com.formdev.flatlaf.ui.FlatTableUI.installUI(FlatTableUI.java:129)
	at burp.theme.BurpTableUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:730)
	at java.desktop/javax.swing.JTable.setUI(JTable.java:3655)
	at java.desktop/javax.swing.JTable.updateUI(JTable.java:3704)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:707)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:645)
	at config.ConfigTable.<init>(ConfigTable.java:37)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:72)
	at burp.Zcp.Zi(Unknown Source)
	at burp.Zu1y.ZY(Unknown Source)
	at burp.Zu11.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by D2550** [comment]
11.2报错
```
java.lang.NullPointerException: Cannot invoke "javax.swing.table.TableModel.addTableModelListener(javax.swing.event.TableModelListener)" because the return value of "javax.swing.JTable.getModel()" is null
	at burp.theme.BurpTableUI.installListeners(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.installUI(BasicTableUI.java:1429)
	at com.formdev.flatlaf.ui.FlatTableUI.installUI(FlatTableUI.java:129)
	at burp.theme.BurpTableUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
	at java.desktop/javax.swing.JTable.setUI(JTable.java:3655)
	at java.desktop/javax.swing.JTable.updateUI(JTable.java:3704)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:707)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:645)
	at config.ConfigTable.<init>(ConfigTable.java:37)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:72)
	at burp.Zgyt.ZZ(Unknown Source)
	at burp.Zh2i.Zs(Unknown Source)
	at burp.Zh2m.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by huajiuqi** [comment]
java.lang.NullPointerException: Cannot invoke "javax.swing.table.TableModel.addTableModelListener(javax.swing.event.TableModelListener)" because the return value of "javax.swing.JTable.getModel()" is null
	at burp.theme.BurpTableUI.installListeners(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.installUI(BasicTableUI.java:1441)
	at com.formdev.flatlaf.ui.FlatTableUI.installUI(FlatTableUI.java:129)
	at burp.theme.BurpTableUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:730)
	at java.desktop/javax.swing.JTable.setUI(JTable.java:3655)
	at java.desktop/javax.swing.JTable.updateUI(JTable.java:3704)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:707)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:645)
	at config.ConfigTable.<init>(ConfigTable.java:37)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:72)
	at burp.Zcp.Zi(Unknown Source)
	at burp.Zu1y.ZY(Unknown Source)
	at burp.Zu11.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 0xVIC** [comment]
Same error:

java.lang.NullPointerException: Cannot invoke "javax.swing.table.TableModel.addTableModelListener(javax.swing.event.TableModelListener)" because the return value of "javax.swing.JTable.getModel()" is null
	at burp.theme.BurpTableUI.installListeners(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.installUI(BasicTableUI.java:1432)
	at com.formdev.flatlaf.ui.FlatTableUI.installUI(FlatTableUI.java:129)
	at burp.theme.BurpTableUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
	at java.desktop/javax.swing.JTable.setUI(JTable.java:3655)
	at java.desktop/javax.swing.JTable.updateUI(JTable.java:3704)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:707)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:645)
	at config.ConfigTable.<init>(ConfigTable.java:37)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:72)
	at burp.Zdh1.Zx(Unknown Source)
	at burp.Zpvs.ZO(Unknown Source)
	at burp.Zpvq.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by bit4woo** [comment]
已修复，可在此处下载对应jar包 https://github.com/bit4woo/knife/actions/runs/7273465081

**Comment by qi7ip** [comment]
Same error:

java.lang.NullPointerException: Cannot invoke "javax.swing.table.TableModel.addTableModelListener(javax.swing.event.TableModelListener)" because the return value of "javax.swing.JTable.getModel()" is null
at burp.theme.BurpTableUI.installListeners(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicTableUI.installUI(BasicTableUI.java:1432)
at com.formdev.flatlaf.ui.FlatTableUI.installUI(FlatTableUI.java:129)
at burp.theme.BurpTableUI.installUI(Unknown Source)
at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
at java.desktop/javax.swing.JTable.setUI(JTable.java:3655)
at java.desktop/javax.swing.JTable.updateUI(JTable.java:3704)
at java.desktop/javax.swing.JTable.(JTable.java:707)
at java.desktop/javax.swing.JTable.(JTable.java:645)
at config.ConfigTable.(ConfigTable.java:37)
at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:72)
at burp.Zdh1.Zx(Unknown Source)
at burp.Zpvs.ZO(Unknown Source)
at burp.Zpvq.lambda$initialiseOnNewThread$0(Unknown Source)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)

https://github.com/bit4woo/knife/actions/runs/7273465081这个好像过期了

**Comment by bit4woo** [comment]
这个问题已修复，下载最新构建的jar包方法如下：

访问Action页面
https://github.com/bit4woo/knife/actions
找到最新成功的构建
![image](https://github.com/bit4woo/knife/assets/8793481/26dc411d-f8e7-42e8-a02d-647c013b1a6a)
点击访问最新构建，找到jar包进行下载
![image](https://github.com/bit4woo/knife/assets/8793481/ecff6e76-100c-4b6e-b4e0-a93a9a9a236e)
