### ISSUE TITLE
最新版burp安装有报错

### ISSUE THREAD

**Issue by Nexolanta** [bit4woo/knife#75]
![image](https://github.com/bit4woo/knife/assets/73454853/6163b479-85a1-44a8-b5a5-b3a6acfd9300)
这个用java17启动burp 安装显示有报错，麻烦作者看下什么原因
![image](https://github.com/bit4woo/knife/assets/73454853/eef5ad35-74eb-4069-8d75-5ec7756101fc)

**Comment by zzqsmile** [comment]
+1

**Comment by Nexolanta** [comment]
> +1

https://github.com/bit4woo/knife 这个也可以  好像是二开的

**Comment by Nexolanta** [comment]
> +1

https://github.com/bit4woo/knife试试这个  我用的是这个

**Comment by doulicau** [comment]
+1

**Comment by soryecker** [comment]
作者不更新了吗

**Comment by zzgxpyy** [comment]
+1

`java.lang.NullPointerException: Cannot invoke "javax.swing.table.TableModel.addTableModelListener(javax.swing.event.TableModelListener)" because the return value of "javax.swing.JTable.getModel()" is null
	at burp.theme.BurpTableUI.installListeners(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.installUI(BasicTableUI.java:1432)
	at com.formdev.flatlaf.ui.FlatTableUI.installUI(FlatTableUI.java:129)
	at burp.theme.BurpTableUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
	at java.desktop/javax.swing.JTable.setUI(JTable.java:3655)
	at java.desktop/javax.swing.JTable.updateUI(JTable.java:3704)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:707)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:645)
	at config.ConfigTable.<init>(ConfigTable.java:37)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:72)
	at burp.Zgyt.ZZ(Unknown Source)
	at burp.Zh2i.Zs(Unknown Source)
	at burp.Zh2m.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
`

**Comment by zzgxpyy** [comment]
https://github.com/bit4woo/knife/actions/runs/7273465081 到期不能下载了。

**Comment by MrADus** [comment]
+1

**Comment by Nexolanta** [comment]
> https://github.com/bit4woo/knife/actions/runs/7273465081变得不能下载了。

https://github.com/bit4woo/knife/releases/tag/v2.2

**Comment by phith0n** [comment]
Action里重新下载了：<https://github.com/bit4woo/knife/actions/runs/8762703631>

**Comment by zzgxpyy** [comment]
> Action里重新下载了：https://github.com/bit4woo/knife/actions/runs/8762703631

谢谢P牛，已成功加载

**Comment by bit4woo** [comment]
问题和 https://github.com/bit4woo/knife/issues/70 相同，请访问这个issue查看解决方法

**Comment by MrADus** [comment]
多谢大佬，可以了

bit4woo ***@***.***> 于2024年4月24日周三 16:36写道：
