### ISSUE TITLE
java高版本报错

### ISSUE THREAD

**Issue by zzqsmile** [bit4woo/knife#80]
java.lang.NullPointerException: Cannot invoke "javax.swing.table.TableModel.addTableModelListener(javax.swing.event.TableModelListener)" because the return value of "javax.swing.JTable.getModel()" is null
	at burp.theme.BurpTableUI.installListeners(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.installUI(BasicTableUI.java:1432)
	at com.formdev.flatlaf.ui.FlatTableUI.installUI(FlatTableUI.java:129)
	at burp.theme.BurpTableUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
	at java.desktop/javax.swing.JTable.setUI(JTable.java:3661)
	at java.desktop/javax.swing.JTable.updateUI(JTable.java:3710)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:707)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:645)
	at config.ConfigTable.<init>(ConfigTable.java:37)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:72)
	at burp.Zx75.ZG(Unknown Source)
	at burp.Z_en.ZZ(Unknown Source)
	at burp.Z_ej.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

mac java17 报错
<img width="483" alt="image" src="https://github.com/bit4woo/knife/assets/38462538/cee60a11-8b69-4009-b6b7-374dae20fc4f">

<img width="1167" alt="image" src="https://github.com/bit4woo/knife/assets/38462538/5c0e65b6-3bbe-4895-a952-8921b4423f31">

**Comment by bit4woo** [comment]
试试最新构建 https://github.com/bit4woo/knife/actions/runs/8812344750/artifacts/1442222632

**Comment by zzqsmile** [comment]
> 试试最新构建 https://github.com/bit4woo/knife/actions/runs/8812344750/artifacts/1442222632


可以

**Comment by bit4woo** [comment]
https://github.com/bit4woo/knife/issues/70 和这个问题相同
